import { describe, expect, test } from 'bun:test';
import { readFileSync } from 'node:fs';
import {
  CLERK_FRONTEND_API_ORIGIN,
  CLERK_IMAGE_ORIGIN,
  CLOUDFLARE_CHALLENGE_ORIGIN,
  PLAUSIBLE_ORIGIN,
  createCspDirectives
} from '../csp.config.js';
import { handle } from '../src/hooks.server';

const requiredHeaders = {
  'x-content-type-options': 'nosniff',
  'referrer-policy': 'strict-origin-when-cross-origin',
  'x-frame-options': 'DENY'
};

describe('baseline response security headers', () => {
  test('SvelteKit responses receive privacy and browser-capability headers', async () => {
    const response = await handle({
      event: { url: new URL('https://schngn.com/app') } as never,
      resolve: async () => new Response('ok')
    });

    for (const [name, value] of Object.entries(requiredHeaders)) {
      expect(response.headers.get(name)).toBe(value);
    }
    expect(response.headers.get('permissions-policy')).toContain('camera=()');
    expect(response.headers.get('permissions-policy')).toContain('geolocation=()');
    expect(response.headers.get('permissions-policy')).toContain('microphone=()');
  });

  test('the hook preserves SvelteKit generated nonce or hash policies', async () => {
    const generatedPolicy = "default-src 'self'; script-src 'self' 'nonce-build-specific'";
    const response = await handle({
      event: { url: new URL('https://schngn.com/app') } as never,
      resolve: async () =>
        new Response('ok', { headers: { 'content-security-policy': generatedPolicy } })
    });

    expect(response.headers.get('content-security-policy')).toBe(generatedPolicy);
  });

  test('Cloudflare static assets receive the same baseline headers', () => {
    const source = readFileSync('apps/web/_headers', 'utf8').toLowerCase();

    for (const [name, value] of Object.entries(requiredHeaders)) {
      expect(source).toContain(`${name}: ${value.toLowerCase()}`);
    }
    expect(source).toContain('permissions-policy:');
    expect(source).not.toContain('content-security-policy:');
    expect(source).toContain('document csp is generated by sveltekit');
  });
});

describe('restrictive application content security policy', () => {
  test('production allows only the app and exact required integration origins', () => {
    const directives = createCspDirectives();

    expect(directives?.['default-src']).toEqual(['self']);
    expect(directives?.['base-uri']).toEqual(['self']);
    expect(directives?.['form-action']).toEqual(['self']);
    expect(directives?.['frame-ancestors']).toEqual(['none']);
    expect(directives?.['object-src']).toEqual(['none']);
    expect(directives?.['media-src']).toEqual(['none']);
    expect(directives?.['script-src']).toEqual([
      'self',
      CLERK_FRONTEND_API_ORIGIN,
      CLOUDFLARE_CHALLENGE_ORIGIN
    ]);
    expect(directives?.['script-src']).not.toContain('unsafe-inline');
    expect(directives?.['script-src']).not.toContain('unsafe-eval');
    expect(directives?.['script-src-attr']).toEqual(['none']);
    expect(directives?.['connect-src']).toEqual([
      'self',
      CLERK_FRONTEND_API_ORIGIN,
      PLAUSIBLE_ORIGIN
    ]);
    expect(directives?.['img-src']).toEqual(['self', 'data:', CLERK_IMAGE_ORIGIN]);
    expect(directives?.['frame-src']).toEqual([CLOUDFLARE_CHALLENGE_ORIGIN]);
    expect(directives?.['worker-src']).toEqual(['self', 'blob:']);
    expect(directives?.['upgrade-insecure-requests']).toBe(true);

    const serialized = JSON.stringify(directives);
    expect(serialized).not.toContain('localhost');
    expect(serialized).not.toContain('127.0.0.1');
    expect(serialized).not.toContain('clerk-telemetry');
    expect(serialized).not.toContain('*.clerk.com');
  });

  test('development adds only Clerk test tenants and local Vite websocket connections', () => {
    const directives = createCspDirectives({ development: true });

    expect(directives?.['script-src']).toContain('https://*.clerk.accounts.dev');
    expect(directives?.['connect-src']).toEqual([
      'self',
      CLERK_FRONTEND_API_ORIGIN,
      'https://*.clerk.accounts.dev',
      PLAUSIBLE_ORIGIN,
      'ws://127.0.0.1:*',
      'ws://localhost:*'
    ]);
    expect(directives?.['upgrade-insecure-requests']).toBeUndefined();
  });

  test('SvelteKit owns document CSP generation in automatic nonce/hash mode', () => {
    const source = readFileSync('apps/web/svelte.config.js', 'utf8');

    expect(source).toContain("mode: 'auto'");
    expect(source).toContain('createCspDirectives({ development })');
  });
});
