import type { Locale } from '$lib/i18n';
export const agentCopy: Record<Locale, Record<"connect" | "requesting" | "returnAddress" | "docs" | "trips" | "limits" | "allow" | "deny" | "signin" | "manage" | "manageIntro" | "empty" | "revoke" | "more" | "back" | "error" | "loading" | "privacy", string>> = {
  "en": {
    "connect": "Connect an agent",
    "requesting": "is requesting access. The application supplies this name.",
    "returnAddress": "Return address",
    "docs": "Read public SCHNGN documentation.",
    "trips": "Read saved account trips: dates, labels, countries, status and IDs. Your agent provider may process and retain this information under its own policies.",
    "limits": "Read-only access expires after 10 minutes. Trips saved only on this device are not shared. You can revoke access at any time.",
    "allow": "Allow read-only access",
    "deny": "Deny",
    "signin": "Sign in to review access",
    "manage": "Agent connections",
    "manageIntro": "Review and revoke access. Every new connection needs your approval.",
    "empty": "No active connections. Start a connection from your agent to share read-only access.",
    "revoke": "Revoke",
    "more": "Load more",
    "back": "Back to account",
    "error": "This request could not be completed. Please restart it from your agent or try again.",
    "loading": "Loading…",
    "privacy": "Privacy"
  },
  "fr": {
    "connect": "Connecter un agent",
    "requesting": "demande un accès. Ce nom est fourni par l’application.",
    "returnAddress": "Adresse de retour",
    "docs": "Lire la documentation publique SCHNGN.",
    "trips": "Lire les voyages enregistrés dans votre compte : dates, libellés, pays, statut et identifiants. Votre fournisseur d’agent peut traiter et conserver ces informations selon ses propres règles.",
    "limits": "L’accès en lecture seule expire après 10 minutes. Les voyages enregistrés uniquement sur cet appareil ne sont pas partagés. Vous pouvez révoquer l’accès à tout moment.",
    "allow": "Autoriser la lecture seule",
    "deny": "Refuser",
    "signin": "Se connecter pour vérifier l’accès",
    "manage": "Connexions des agents",
    "manageIntro": "Vérifiez et révoquez les accès. Chaque nouvelle connexion nécessite votre accord.",
    "empty": "Aucune connexion active. Démarrez une connexion depuis votre agent pour partager un accès en lecture seule.",
    "revoke": "Révoquer",
    "more": "Afficher plus",
    "back": "Retour au compte",
    "error": "Cette demande n’a pas abouti. Relancez-la depuis votre agent ou réessayez.",
    "loading": "Chargement…",
    "privacy": "Confidentialité"
  },
  "de": {
    "connect": "Einen Agenten verbinden",
    "requesting": "fordert Zugriff an. Diesen Namen gibt die Anwendung an.",
    "returnAddress": "Rückleitungsadresse",
    "docs": "Öffentliche SCHNGN-Dokumentation lesen.",
    "trips": "Im Konto gespeicherte Reisen lesen: Daten, Bezeichnungen, Länder, Status und IDs. Ihr Agentenanbieter kann diese Informationen gemäß seinen eigenen Richtlinien verarbeiten und speichern.",
    "limits": "Der Lesezugriff läuft nach 10 Minuten ab. Nur auf diesem Gerät gespeicherte Reisen werden nicht geteilt. Sie können den Zugriff jederzeit widerrufen.",
    "allow": "Lesezugriff erlauben",
    "deny": "Ablehnen",
    "signin": "Anmelden und Zugriff prüfen",
    "manage": "Agentenverbindungen",
    "manageIntro": "Zugriffe prüfen und widerrufen. Jede neue Verbindung erfordert Ihre Zustimmung.",
    "empty": "Keine aktiven Verbindungen. Starten Sie eine Verbindung über Ihren Agenten, um Lesezugriff zu teilen.",
    "revoke": "Widerrufen",
    "more": "Mehr laden",
    "back": "Zurück zum Konto",
    "error": "Diese Anfrage konnte nicht abgeschlossen werden. Starten Sie sie über Ihren Agenten neu oder versuchen Sie es erneut.",
    "loading": "Wird geladen…",
    "privacy": "Datenschutz"
  },
  "es": {
    "connect": "Conectar un agente",
    "requesting": "solicita acceso. La aplicación proporciona este nombre.",
    "returnAddress": "Dirección de retorno",
    "docs": "Leer la documentación pública de SCHNGN.",
    "trips": "Leer los viajes guardados en tu cuenta: fechas, etiquetas, países, estado e identificadores. Tu proveedor de agente puede procesar y conservar esta información según sus propias políticas.",
    "limits": "El acceso de solo lectura caduca a los 10 minutos. No se comparten los viajes guardados únicamente en este dispositivo. Puedes revocar el acceso en cualquier momento.",
    "allow": "Permitir solo lectura",
    "deny": "Denegar",
    "signin": "Iniciar sesión para revisar el acceso",
    "manage": "Conexiones de agentes",
    "manageIntro": "Revisa y revoca accesos. Cada nueva conexión necesita tu aprobación.",
    "empty": "No hay conexiones activas. Inicia una conexión desde tu agente para compartir acceso de solo lectura.",
    "revoke": "Revocar",
    "more": "Cargar más",
    "back": "Volver a la cuenta",
    "error": "No se pudo completar la solicitud. Reiníciala desde tu agente o inténtalo de nuevo.",
    "loading": "Cargando…",
    "privacy": "Privacidad"
  },
  "it": {
    "connect": "Collega un agente",
    "requesting": "richiede l’accesso. Il nome è fornito dall’applicazione.",
    "returnAddress": "Indirizzo di ritorno",
    "docs": "Leggere la documentazione pubblica di SCHNGN.",
    "trips": "Leggere i viaggi salvati nel tuo account: date, etichette, paesi, stato e identificativi. Il fornitore del tuo agente può trattare e conservare queste informazioni secondo le proprie politiche.",
    "limits": "L’accesso in sola lettura scade dopo 10 minuti. I viaggi salvati solo su questo dispositivo non vengono condivisi. Puoi revocare l’accesso in qualsiasi momento.",
    "allow": "Consenti sola lettura",
    "deny": "Nega",
    "signin": "Accedi per verificare l’accesso",
    "manage": "Connessioni degli agenti",
    "manageIntro": "Verifica e revoca gli accessi. Ogni nuova connessione richiede la tua approvazione.",
    "empty": "Nessuna connessione attiva. Avvia una connessione dal tuo agente per condividere l’accesso in sola lettura.",
    "revoke": "Revoca",
    "more": "Carica altro",
    "back": "Torna all’account",
    "error": "Impossibile completare la richiesta. Riavviala dal tuo agente o riprova.",
    "loading": "Caricamento…",
    "privacy": "Privacy"
  },
  "pt-br": {
    "connect": "Conectar um agente",
    "requesting": "está solicitando acesso. O aplicativo fornece este nome.",
    "returnAddress": "Endereço de retorno",
    "docs": "Ler a documentação pública do SCHNGN.",
    "trips": "Ler viagens salvas na sua conta: datas, nomes, países, status e identificadores. O provedor do seu agente pode processar e reter essas informações conforme suas próprias políticas.",
    "limits": "O acesso somente de leitura expira após 10 minutos. Viagens salvas apenas neste dispositivo não são compartilhadas. Você pode revogar o acesso a qualquer momento.",
    "allow": "Permitir somente leitura",
    "deny": "Negar",
    "signin": "Entrar para revisar o acesso",
    "manage": "Conexões de agentes",
    "manageIntro": "Revise e revogue acessos. Cada nova conexão precisa da sua aprovação.",
    "empty": "Nenhuma conexão ativa. Inicie uma conexão pelo seu agente para compartilhar acesso somente de leitura.",
    "revoke": "Revogar",
    "more": "Carregar mais",
    "back": "Voltar à conta",
    "error": "Não foi possível concluir a solicitação. Reinicie pelo seu agente ou tente novamente.",
    "loading": "Carregando…",
    "privacy": "Privacidade"
  },
  "ru": {
    "connect": "Подключить агента",
    "requesting": "запрашивает доступ. Это имя указано приложением.",
    "returnAddress": "Адрес возврата",
    "docs": "Читать общедоступную документацию SCHNGN.",
    "trips": "Читать поездки, сохранённые в аккаунте: даты, названия, страны, статус и идентификаторы. Поставщик вашего агента может обрабатывать и хранить эти сведения по своим правилам.",
    "limits": "Доступ только для чтения истекает через 10 минут. Поездки, сохранённые только на этом устройстве, не передаются. Доступ можно отозвать в любое время.",
    "allow": "Разрешить чтение",
    "deny": "Отказать",
    "signin": "Войти для проверки доступа",
    "manage": "Подключения агентов",
    "manageIntro": "Проверяйте и отзывайте доступ. Каждое новое подключение требует вашего согласия.",
    "empty": "Активных подключений нет. Начните подключение из своего агента, чтобы предоставить доступ для чтения.",
    "revoke": "Отозвать",
    "more": "Загрузить ещё",
    "back": "Вернуться в аккаунт",
    "error": "Не удалось выполнить запрос. Начните его заново из своего агента или повторите попытку.",
    "loading": "Загрузка…",
    "privacy": "Конфиденциальность"
  },
  "uk": {
    "connect": "Підключити агента",
    "requesting": "запитує доступ. Цю назву вказує застосунок.",
    "returnAddress": "Адреса повернення",
    "docs": "Читати загальнодоступну документацію SCHNGN.",
    "trips": "Читати поїздки, збережені в обліковому записі: дати, назви, країни, статус та ідентифікатори. Постачальник вашого агента може обробляти й зберігати ці відомості за власними правилами.",
    "limits": "Доступ лише для читання спливає через 10 хвилин. Поїздки, збережені лише на цьому пристрої, не передаються. Доступ можна відкликати будь-коли.",
    "allow": "Дозволити читання",
    "deny": "Відмовити",
    "signin": "Увійти для перевірки доступу",
    "manage": "Підключення агентів",
    "manageIntro": "Перевіряйте та відкликайте доступ. Кожне нове підключення потребує вашої згоди.",
    "empty": "Активних підключень немає. Почніть підключення зі свого агента, щоб надати доступ для читання.",
    "revoke": "Відкликати",
    "more": "Завантажити ще",
    "back": "До облікового запису",
    "error": "Не вдалося виконати запит. Почніть його знову зі свого агента або повторіть спробу.",
    "loading": "Завантаження…",
    "privacy": "Конфіденційність"
  },
  "tr": {
    "connect": "Bir ajan bağla",
    "requesting": "erişim istiyor. Bu ad uygulama tarafından belirtilmiştir.",
    "returnAddress": "Dönüş adresi",
    "docs": "Herkese açık SCHNGN belgelerini oku.",
    "trips": "Hesabınıza kaydedilmiş seyahatleri oku: tarihler, etiketler, ülkeler, durum ve kimlikler. Ajan sağlayıcınız bu bilgileri kendi politikalarına göre işleyebilir ve saklayabilir.",
    "limits": "Salt okunur erişim 10 dakika sonra sona erer. Yalnızca bu cihazda kayıtlı seyahatler paylaşılmaz. Erişimi istediğiniz zaman iptal edebilirsiniz.",
    "allow": "Salt okunur erişime izin ver",
    "deny": "Reddet",
    "signin": "Erişimi incelemek için giriş yap",
    "manage": "Ajan bağlantıları",
    "manageIntro": "Erişimleri inceleyin ve iptal edin. Her yeni bağlantı onayınızı gerektirir.",
    "empty": "Etkin bağlantı yok. Salt okunur erişimi paylaşmak için ajanınızdan bir bağlantı başlatın.",
    "revoke": "İptal et",
    "more": "Daha fazla yükle",
    "back": "Hesaba dön",
    "error": "İstek tamamlanamadı. Ajanınızdan yeniden başlatın veya tekrar deneyin.",
    "loading": "Yükleniyor…",
    "privacy": "Gizlilik"
  },
  "sr": {
    "connect": "Poveži agenta",
    "requesting": "traži pristup. Ovaj naziv navodi aplikacija.",
    "returnAddress": "Adresa za povratak",
    "docs": "Čitanje javne SCHNGN dokumentacije.",
    "trips": "Čitanje putovanja sačuvanih na nalogu: datumi, nazivi, zemlje, status i identifikatori. Provajder vašeg agenta može obrađivati i čuvati ove podatke prema svojim pravilima.",
    "limits": "Pristup samo za čitanje ističe posle 10 minuta. Putovanja sačuvana samo na ovom uređaju se ne dele. Pristup možete opozvati u svakom trenutku.",
    "allow": "Dozvoli samo čitanje",
    "deny": "Odbij",
    "signin": "Prijavi se i proveri pristup",
    "manage": "Veze sa agentima",
    "manageIntro": "Pregledajte i opozovite pristupe. Svaka nova veza zahteva vaše odobrenje.",
    "empty": "Nema aktivnih veza. Pokrenite povezivanje iz svog agenta da biste omogućili pristup samo za čitanje.",
    "revoke": "Opozovi",
    "more": "Učitaj još",
    "back": "Nazad na nalog",
    "error": "Zahtev nije završen. Pokrenite ga ponovo iz svog agenta ili pokušajte opet.",
    "loading": "Učitavanje…",
    "privacy": "Privatnost"
  },
  "sq": {
    "connect": "Lidh një agjent",
    "requesting": "po kërkon qasje. Ky emër jepet nga aplikacioni.",
    "returnAddress": "Adresa e kthimit",
    "docs": "Lexo dokumentacionin publik të SCHNGN.",
    "trips": "Lexo udhëtimet e ruajtura në llogarinë tënde: datat, emërtimet, shtetet, statusin dhe identifikuesit. Ofruesi i agjentit mund t’i përpunojë dhe ruajë këto informacione sipas politikave të veta.",
    "limits": "Qasja vetëm për lexim skadon pas 10 minutash. Udhëtimet e ruajtura vetëm në këtë pajisje nuk ndahen. Mund ta revokosh qasjen në çdo kohë.",
    "allow": "Lejo vetëm leximin",
    "deny": "Refuzo",
    "signin": "Hyr për të shqyrtuar qasjen",
    "manage": "Lidhjet e agjentëve",
    "manageIntro": "Shqyrto dhe revoko qasjet. Çdo lidhje e re kërkon miratimin tënd.",
    "empty": "Nuk ka lidhje aktive. Fillo një lidhje nga agjenti yt për të ndarë qasje vetëm për lexim.",
    "revoke": "Revoko",
    "more": "Ngarko më shumë",
    "back": "Kthehu te llogaria",
    "error": "Kërkesa nuk u përfundua. Rinis nga agjenti yt ose provo përsëri.",
    "loading": "Duke ngarkuar…",
    "privacy": "Privatësia"
  },
  "ka": {
    "connect": "აგენტის დაკავშირება",
    "requesting": "ითხოვს წვდომას. ეს სახელი მითითებულია აპლიკაციის მიერ.",
    "returnAddress": "დაბრუნების მისამართი",
    "docs": "SCHNGN-ის საჯარო დოკუმენტაციის წაკითხვა.",
    "trips": "ანგარიშში შენახული მოგზაურობების წაკითხვა: თარიღები, სახელები, ქვეყნები, სტატუსი და იდენტიფიკატორები. აგენტის მომწოდებელს შეუძლია ამ ინფორმაციის დამუშავება და შენახვა საკუთარი წესების შესაბამისად.",
    "limits": "მხოლოდ წაკითხვის წვდომა 10 წუთში იწურება. მხოლოდ ამ მოწყობილობაზე შენახული მოგზაურობები არ გაზიარდება. წვდომის გაუქმება ნებისმიერ დროს შეგიძლიათ.",
    "allow": "წაკითხვის დაშვება",
    "deny": "უარყოფა",
    "signin": "შედით წვდომის შესამოწმებლად",
    "manage": "აგენტების კავშირები",
    "manageIntro": "შეამოწმეთ და გააუქმეთ წვდომები. ყოველი ახალი კავშირი თქვენს თანხმობას მოითხოვს.",
    "empty": "აქტიური კავშირები არ არის. მხოლოდ წაკითხვის წვდომის გასაზიარებლად დაიწყეთ დაკავშირება თქვენი აგენტიდან.",
    "revoke": "გაუქმება",
    "more": "მეტის ჩატვირთვა",
    "back": "ანგარიშზე დაბრუნება",
    "error": "მოთხოვნა ვერ შესრულდა. თავიდან დაიწყეთ თქვენი აგენტიდან ან სცადეთ ხელახლა.",
    "loading": "იტვირთება…",
    "privacy": "კონფიდენციალურობა"
  },
  "zh-cn": {
    "connect": "连接代理",
    "requesting": "正在请求访问。此名称由应用提供。",
    "returnAddress": "返回地址",
    "docs": "读取 SCHNGN 的公开文档。",
    "trips": "读取保存在账户中的行程：日期、标签、国家、状态和标识符。您的代理服务商可能按其自身政策处理和保留这些信息。",
    "limits": "只读权限将在 10 分钟后到期。仅保存在此设备上的行程不会共享。您可以随时撤销权限。",
    "allow": "允许只读访问",
    "deny": "拒绝",
    "signin": "登录以查看权限",
    "manage": "代理连接",
    "manageIntro": "查看并撤销权限。每次新连接都需要您的批准。",
    "empty": "没有有效连接。请从您的代理发起连接，以共享只读权限。",
    "revoke": "撤销",
    "more": "加载更多",
    "back": "返回账户",
    "error": "无法完成此请求。请从您的代理重新发起，或重试。",
    "loading": "正在加载…",
    "privacy": "隐私"
  },
  "ja": {
    "connect": "エージェントを接続",
    "requesting": "がアクセスを要求しています。この名前はアプリが指定したものです。",
    "returnAddress": "戻り先のアドレス",
    "docs": "SCHNGN の公開ドキュメントを読む。",
    "trips": "アカウントに保存された旅行の日時、ラベル、国、状態、IDを読む。エージェントの提供元は、独自の方針に基づいてこの情報を処理・保持する場合があります。",
    "limits": "読み取り専用のアクセスは10分後に失効します。この端末だけに保存された旅行は共有されません。アクセスはいつでも取り消せます。",
    "allow": "読み取り専用アクセスを許可",
    "deny": "拒否",
    "signin": "ログインしてアクセスを確認",
    "manage": "エージェントの接続",
    "manageIntro": "アクセスを確認・取り消します。新しい接続には毎回あなたの承認が必要です。",
    "empty": "有効な接続はありません。エージェント側から接続を開始して、読み取り専用アクセスを共有してください。",
    "revoke": "取り消す",
    "more": "さらに読み込む",
    "back": "アカウントに戻る",
    "error": "リクエストを完了できませんでした。エージェント側からやり直すか、再試行してください。",
    "loading": "読み込み中…",
    "privacy": "プライバシー"
  },
  "ko": {
    "connect": "에이전트 연결",
    "requesting": "에서 접근을 요청합니다. 이 이름은 앱이 제공한 것입니다.",
    "returnAddress": "돌아갈 주소",
    "docs": "SCHNGN 공개 문서를 읽습니다.",
    "trips": "계정에 저장된 여행의 날짜, 이름, 국가, 상태 및 ID를 읽습니다. 에이전트 제공업체는 자체 정책에 따라 이 정보를 처리하고 보관할 수 있습니다.",
    "limits": "읽기 전용 권한은 10분 후 만료됩니다. 이 기기에만 저장된 여행은 공유되지 않습니다. 언제든지 권한을 취소할 수 있습니다.",
    "allow": "읽기 전용 접근 허용",
    "deny": "거부",
    "signin": "로그인하여 접근 확인",
    "manage": "에이전트 연결 관리",
    "manageIntro": "접근을 검토하고 취소하세요. 새 연결마다 승인이 필요합니다.",
    "empty": "활성 연결이 없습니다. 에이전트에서 연결을 시작하여 읽기 전용 접근을 공유하세요.",
    "revoke": "취소",
    "more": "더 불러오기",
    "back": "계정으로 돌아가기",
    "error": "요청을 완료하지 못했습니다. 에이전트에서 다시 시작하거나 재시도하세요.",
    "loading": "불러오는 중…",
    "privacy": "개인정보 보호"
  },
  "he": {
    "connect": "חיבור סוכן",
    "requesting": "מבקש גישה. השם הזה נמסר על ידי האפליקציה.",
    "returnAddress": "כתובת חזרה",
    "docs": "קריאת התיעוד הציבורי של SCHNGN.",
    "trips": "קריאת נסיעות שנשמרו בחשבון: תאריכים, תוויות, מדינות, מצב ומזהים. ספק הסוכן עשוי לעבד ולשמור את המידע לפי המדיניות שלו.",
    "limits": "הגישה לקריאה בלבד פגה לאחר 10 דקות. נסיעות שנשמרו רק במכשיר הזה לא ישותפו. אפשר לבטל את הגישה בכל עת.",
    "allow": "אישור גישה לקריאה בלבד",
    "deny": "דחייה",
    "signin": "כניסה לבדיקת הגישה",
    "manage": "חיבורי סוכנים",
    "manageIntro": "בדיקה וביטול של הרשאות גישה. כל חיבור חדש דורש את אישורך.",
    "empty": "אין חיבורים פעילים. יש להתחיל חיבור מתוך הסוכן כדי לשתף גישה לקריאה בלבד.",
    "revoke": "ביטול",
    "more": "טעינת עוד",
    "back": "חזרה לחשבון",
    "error": "לא ניתן להשלים את הבקשה. יש להתחיל מחדש מתוך הסוכן או לנסות שוב.",
    "loading": "בטעינה…",
    "privacy": "פרטיות"
  },
  "ar": {
    "connect": "ربط وكيل",
    "requesting": "يطلب الوصول. يقدّم التطبيق هذا الاسم.",
    "returnAddress": "عنوان العودة",
    "docs": "قراءة وثائق SCHNGN العامة.",
    "trips": "قراءة الرحلات المحفوظة في حسابك: التواريخ والتسميات والبلدان والحالة والمعرّفات. قد يعالج مزوّد وكيلك هذه المعلومات ويحتفظ بها وفقًا لسياساته الخاصة.",
    "limits": "تنتهي صلاحية الوصول للقراءة فقط بعد 10 دقائق. لا تتم مشاركة الرحلات المحفوظة على هذا الجهاز فقط. يمكنك إلغاء الوصول في أي وقت.",
    "allow": "السماح بالقراءة فقط",
    "deny": "رفض",
    "signin": "تسجيل الدخول لمراجعة الوصول",
    "manage": "اتصالات الوكلاء",
    "manageIntro": "راجع الوصول وألغه. كل اتصال جديد يحتاج إلى موافقتك.",
    "empty": "لا توجد اتصالات نشطة. ابدأ اتصالًا من وكيلك لمشاركة الوصول للقراءة فقط.",
    "revoke": "إلغاء",
    "more": "تحميل المزيد",
    "back": "العودة إلى الحساب",
    "error": "تعذّر إكمال الطلب. أعد بدءه من وكيلك أو حاول مرة أخرى.",
    "loading": "جارٍ التحميل…",
    "privacy": "الخصوصية"
  }
};
