import type { Locale } from './locales';

const en = {
  navOverview: 'Overview', navTrips: 'Trips', navPlanner: 'Planner', navProof: 'Proof', navReturns: 'Returns', navReport: 'Report', navAccount: 'Account',
  headTitle: 'SCHNGN app — private Schengen planner', headDescription: 'Calculate Schengen 90/180-day plans locally, with optional consented account sync.',
  appSections: 'App sections', openAccount: 'Open Account', storageAttention: 'Browser storage needs attention', planningOnly: 'Planning calculator only', officialSources: 'Official source links', dismiss: 'Dismiss',
  loadingTrips: 'Loading your trips…', readingLocal: 'Reading local data from this browser.', noTripData: 'No trip data stored', startDates: 'Start with your travel dates',
  emptyCopy: 'Add past and booked stays to get a real 90/180-day answer. SCHNGN starts empty, so no example itinerary can affect your result.',
  firstResult: 'Your first useful result', firstResultCopy: 'Add entry and exit dates for one stay. Both days count. Your dates remain in this browser.',
  addFirst: 'Add your first trip', tryWhatIf: 'Try a what-if plan', latestSafeExit: 'Latest safe exit', daysUsed: 'Days used', rollingWindow: 'Rolling 180-day window',
  needsAttention: 'What needs attention', whyAnswer: 'Why this answer', addTrip: 'Add trip', showCalculation: 'Show calculation', planAnother: 'Plan another trip',
  accountLoading: 'Account…', localOnly: 'Local only', signIn: 'Sign in', syncing: 'Syncing…', synced: 'Synced', syncPaused: 'Sync paused', reviewSync: 'Review sync', accountReady: 'Account ready'
} as const;

export type AppUiKey = keyof typeof en;
type AppCatalog = Record<AppUiKey, string>;

const fr: AppCatalog = {
  navOverview:'Aperçu',navTrips:'Voyages',navPlanner:'Planifier',navProof:'Preuve',navReturns:'Retours',navReport:'Rapport',navAccount:'Compte',headTitle:'Application SCHNGN — planificateur Schengen privé',headDescription:'Calculez localement vos plans Schengen 90/180 avec synchronisation de compte facultative.',appSections:'Sections de l’application',openAccount:'Ouvrir le compte',storageAttention:'Le stockage du navigateur nécessite votre attention',planningOnly:'Calculateur de planification uniquement',officialSources:'Liens vers les sources officielles',dismiss:'Fermer',loadingTrips:'Chargement de vos voyages…',readingLocal:'Lecture des données locales de ce navigateur.',noTripData:'Aucune donnée de voyage stockée',startDates:'Commencez par vos dates de voyage',emptyCopy:'Ajoutez vos séjours passés et réservés pour obtenir un vrai résultat 90/180. SCHNGN démarre vide.',firstResult:'Votre premier résultat utile',firstResultCopy:'Ajoutez les dates d’entrée et de sortie d’un séjour. Les deux jours comptent. Vos dates restent dans ce navigateur.',addFirst:'Ajouter votre premier voyage',tryWhatIf:'Essayer une simulation',latestSafeExit:'Dernière sortie sûre',daysUsed:'Jours utilisés',rollingWindow:'Fenêtre glissante de 180 jours',needsAttention:'Ce qui demande votre attention',whyAnswer:'Pourquoi ce résultat',addTrip:'Ajouter un voyage',showCalculation:'Afficher le calcul',planAnother:'Planifier un autre voyage',accountLoading:'Compte…',localOnly:'Local uniquement',signIn:'Se connecter',syncing:'Synchronisation…',synced:'Synchronisé',syncPaused:'Synchronisation suspendue',reviewSync:'Vérifier la synchronisation',accountReady:'Compte prêt'
};
const de: AppCatalog = {
  navOverview:'Übersicht',navTrips:'Reisen',navPlanner:'Planer',navProof:'Nachweis',navReturns:'Rückkehr',navReport:'Bericht',navAccount:'Konto',headTitle:'SCHNGN-App — privater Schengen-Planer',headDescription:'Schengen-90/180-Pläne lokal berechnen, optional mit Kontosynchronisierung.',appSections:'App-Bereiche',openAccount:'Konto öffnen',storageAttention:'Browserspeicher benötigt Aufmerksamkeit',planningOnly:'Nur Planungsrechner',officialSources:'Offizielle Quellen',dismiss:'Schließen',loadingTrips:'Reisen werden geladen…',readingLocal:'Lokale Daten dieses Browsers werden gelesen.',noTripData:'Keine Reisedaten gespeichert',startDates:'Beginnen Sie mit Ihren Reisedaten',emptyCopy:'Fügen Sie vergangene und gebuchte Aufenthalte hinzu, um ein echtes 90/180-Ergebnis zu erhalten. SCHNGN beginnt leer.',firstResult:'Ihr erstes nützliches Ergebnis',firstResultCopy:'Fügen Sie Ein- und Ausreisedatum eines Aufenthalts hinzu. Beide Tage zählen. Ihre Daten bleiben in diesem Browser.',addFirst:'Erste Reise hinzufügen',tryWhatIf:'Was-wäre-wenn testen',latestSafeExit:'Späteste sichere Ausreise',daysUsed:'Genutzte Tage',rollingWindow:'Rollierendes 180-Tage-Fenster',needsAttention:'Was Aufmerksamkeit braucht',whyAnswer:'Warum dieses Ergebnis',addTrip:'Reise hinzufügen',showCalculation:'Berechnung anzeigen',planAnother:'Weitere Reise planen',accountLoading:'Konto…',localOnly:'Nur lokal',signIn:'Anmelden',syncing:'Synchronisierung…',synced:'Synchronisiert',syncPaused:'Sync pausiert',reviewSync:'Sync prüfen',accountReady:'Konto bereit'
};
const es: AppCatalog = {
  navOverview:'Resumen',navTrips:'Viajes',navPlanner:'Planificador',navProof:'Prueba',navReturns:'Devoluciones',navReport:'Informe',navAccount:'Cuenta',headTitle:'Aplicación SCHNGN — planificador Schengen privado',headDescription:'Calcula planes Schengen 90/180 localmente, con sincronización opcional de cuenta.',appSections:'Secciones de la aplicación',openAccount:'Abrir cuenta',storageAttention:'El almacenamiento del navegador necesita atención',planningOnly:'Solo calculadora de planificación',officialSources:'Enlaces a fuentes oficiales',dismiss:'Cerrar',loadingTrips:'Cargando tus viajes…',readingLocal:'Leyendo datos locales de este navegador.',noTripData:'No hay datos de viaje guardados',startDates:'Empieza con las fechas de tu viaje',emptyCopy:'Añade estancias pasadas y reservadas para obtener un resultado 90/180 real. SCHNGN empieza vacío.',firstResult:'Tu primer resultado útil',firstResultCopy:'Añade las fechas de entrada y salida de una estancia. Ambos días cuentan. Tus fechas permanecen en este navegador.',addFirst:'Añadir tu primer viaje',tryWhatIf:'Probar una simulación',latestSafeExit:'Última salida segura',daysUsed:'Días usados',rollingWindow:'Ventana móvil de 180 días',needsAttention:'Lo que requiere atención',whyAnswer:'Por qué este resultado',addTrip:'Añadir viaje',showCalculation:'Mostrar cálculo',planAnother:'Planificar otro viaje',accountLoading:'Cuenta…',localOnly:'Solo local',signIn:'Iniciar sesión',syncing:'Sincronizando…',synced:'Sincronizado',syncPaused:'Sincronización pausada',reviewSync:'Revisar sincronización',accountReady:'Cuenta lista'
};
const it: AppCatalog = {
  navOverview:'Panoramica',navTrips:'Viaggi',navPlanner:'Pianificatore',navProof:'Prova',navReturns:'Rientri',navReport:'Rapporto',navAccount:'Account',headTitle:'App SCHNGN — pianificatore Schengen privato',headDescription:'Calcola localmente i piani Schengen 90/180 con sincronizzazione account facoltativa.',appSections:'Sezioni dell’app',openAccount:'Apri account',storageAttention:'La memoria del browser richiede attenzione',planningOnly:'Solo calcolatore di pianificazione',officialSources:'Link alle fonti ufficiali',dismiss:'Chiudi',loadingTrips:'Caricamento dei viaggi…',readingLocal:'Lettura dei dati locali da questo browser.',noTripData:'Nessun dato di viaggio salvato',startDates:'Inizia dalle date del viaggio',emptyCopy:'Aggiungi soggiorni passati e prenotati per ottenere un vero risultato 90/180. SCHNGN parte vuoto.',firstResult:'Il tuo primo risultato utile',firstResultCopy:'Aggiungi le date di ingresso e uscita di un soggiorno. Entrambi i giorni contano. Le date restano nel browser.',addFirst:'Aggiungi il primo viaggio',tryWhatIf:'Prova una simulazione',latestSafeExit:'Ultima uscita sicura',daysUsed:'Giorni usati',rollingWindow:'Finestra mobile di 180 giorni',needsAttention:'Cosa richiede attenzione',whyAnswer:'Perché questo risultato',addTrip:'Aggiungi viaggio',showCalculation:'Mostra il calcolo',planAnother:'Pianifica un altro viaggio',accountLoading:'Account…',localOnly:'Solo locale',signIn:'Accedi',syncing:'Sincronizzazione…',synced:'Sincronizzato',syncPaused:'Sincronizzazione sospesa',reviewSync:'Verifica sincronizzazione',accountReady:'Account pronto'
};
const ru: AppCatalog = {
  navOverview:'Обзор',navTrips:'Поездки',navPlanner:'Планировщик',navProof:'Расчёт',navReturns:'Возврат дней',navReport:'Отчёт',navAccount:'Аккаунт',headTitle:'Приложение SCHNGN — приватный планировщик Шенгена',headDescription:'Локальный расчёт планов Шенген 90/180 с необязательной синхронизацией аккаунта.',appSections:'Разделы приложения',openAccount:'Открыть аккаунт',storageAttention:'Хранилище браузера требует внимания',planningOnly:'Только планировочный калькулятор',officialSources:'Официальные источники',dismiss:'Закрыть',loadingTrips:'Загрузка поездок…',readingLocal:'Чтение локальных данных этого браузера.',noTripData:'Данные поездок не сохранены',startDates:'Начните с дат поездки',emptyCopy:'Добавьте прошлые и забронированные поездки, чтобы получить расчёт 90/180. SCHNGN начинает с пустого списка.',firstResult:'Ваш первый полезный результат',firstResultCopy:'Добавьте даты въезда и выезда одной поездки. Оба дня учитываются. Даты остаются в браузере.',addFirst:'Добавить первую поездку',tryWhatIf:'Проверить сценарий',latestSafeExit:'Последний безопасный выезд',daysUsed:'Использовано дней',rollingWindow:'Скользящее окно 180 дней',needsAttention:'Что требует внимания',whyAnswer:'Почему такой результат',addTrip:'Добавить поездку',showCalculation:'Показать расчёт',planAnother:'Спланировать ещё поездку',accountLoading:'Аккаунт…',localOnly:'Только локально',signIn:'Войти',syncing:'Синхронизация…',synced:'Синхронизировано',syncPaused:'Синхронизация приостановлена',reviewSync:'Проверить синхронизацию',accountReady:'Аккаунт готов'
};
const tr: AppCatalog = {
  navOverview:'Genel bakış',navTrips:'Seyahatler',navPlanner:'Planlayıcı',navProof:'Kanıt',navReturns:'Geri dönen günler',navReport:'Rapor',navAccount:'Hesap',headTitle:'SCHNGN uygulaması — özel Schengen planlayıcı',headDescription:'Schengen 90/180 planlarını isteğe bağlı hesap eşitlemesiyle yerel olarak hesaplayın.',appSections:'Uygulama bölümleri',openAccount:'Hesabı aç',storageAttention:'Tarayıcı depolaması ilgi gerektiriyor',planningOnly:'Yalnızca planlama hesaplayıcısı',officialSources:'Resmi kaynak bağlantıları',dismiss:'Kapat',loadingTrips:'Seyahatleriniz yükleniyor…',readingLocal:'Bu tarayıcıdaki yerel veriler okunuyor.',noTripData:'Seyahat verisi saklanmıyor',startDates:'Seyahat tarihlerinizle başlayın',emptyCopy:'Gerçek bir 90/180 sonucu için geçmiş ve rezerve edilmiş konaklamaları ekleyin. SCHNGN boş başlar.',firstResult:'İlk yararlı sonucunuz',firstResultCopy:'Bir konaklamanın giriş ve çıkış tarihlerini ekleyin. İki gün de sayılır. Tarihleriniz bu tarayıcıda kalır.',addFirst:'İlk seyahatinizi ekleyin',tryWhatIf:'Bir senaryo deneyin',latestSafeExit:'En geç güvenli çıkış',daysUsed:'Kullanılan gün',rollingWindow:'Kayan 180 günlük pencere',needsAttention:'Dikkat edilmesi gerekenler',whyAnswer:'Bu sonucun nedeni',addTrip:'Seyahat ekle',showCalculation:'Hesabı göster',planAnother:'Başka seyahat planla',accountLoading:'Hesap…',localOnly:'Yalnızca yerel',signIn:'Giriş yap',syncing:'Eşitleniyor…',synced:'Eşitlendi',syncPaused:'Eşitleme duraklatıldı',reviewSync:'Eşitlemeyi incele',accountReady:'Hesap hazır'
};
const he: AppCatalog = {
  navOverview:'סקירה',navTrips:'נסיעות',navPlanner:'תכנון',navProof:'הוכחה',navReturns:'ימים חוזרים',navReport:'דוח',navAccount:'חשבון',headTitle:'אפליקציית SCHNGN — מתכנן שנגן פרטי',headDescription:'חישוב תוכניות שנגן 90/180 באופן מקומי, עם סנכרון חשבון אופציונלי.',appSections:'חלקי האפליקציה',openAccount:'פתיחת החשבון',storageAttention:'אחסון הדפדפן דורש תשומת לב',planningOnly:'מחשבון תכנון בלבד',officialSources:'קישורים למקורות רשמיים',dismiss:'סגירה',loadingTrips:'הנסיעות נטענות…',readingLocal:'קורא נתונים מקומיים מהדפדפן.',noTripData:'לא נשמרו נתוני נסיעות',startDates:'מתחילים בתאריכי הנסיעה',emptyCopy:'הוסיפו שהיות קודמות ומוזמנות כדי לקבל תשובת 90/180 אמיתית. SCHNGN מתחיל ריק.',firstResult:'התוצאה השימושית הראשונה',firstResultCopy:'הוסיפו תאריכי כניסה ויציאה לשהות אחת. שני הימים נספרים. התאריכים נשארים בדפדפן.',addFirst:'הוספת הנסיעה הראשונה',tryWhatIf:'בדיקת תרחיש',latestSafeExit:'יציאה בטוחה אחרונה',daysUsed:'ימים שנוצלו',rollingWindow:'חלון מתגלגל של 180 יום',needsAttention:'מה דורש תשומת לב',whyAnswer:'למה זו התוצאה',addTrip:'הוספת נסיעה',showCalculation:'הצגת החישוב',planAnother:'תכנון נסיעה נוספת',accountLoading:'חשבון…',localOnly:'מקומי בלבד',signIn:'כניסה',syncing:'בסנכרון…',synced:'מסונכרן',syncPaused:'הסנכרון מושהה',reviewSync:'בדיקת הסנכרון',accountReady:'החשבון מוכן'
};
const ar: AppCatalog = {
  navOverview:'نظرة عامة',navTrips:'الرحلات',navPlanner:'المخطط',navProof:'الدليل',navReturns:'الأيام العائدة',navReport:'التقرير',navAccount:'الحساب',headTitle:'تطبيق SCHNGN — مخطط شنغن خاص',headDescription:'احسب خطط شنغن 90/180 محليًا مع مزامنة حساب اختيارية.',appSections:'أقسام التطبيق',openAccount:'فتح الحساب',storageAttention:'تخزين المتصفح يحتاج إلى الانتباه',planningOnly:'حاسبة تخطيط فقط',officialSources:'روابط المصادر الرسمية',dismiss:'إغلاق',loadingTrips:'جارٍ تحميل رحلاتك…',readingLocal:'تتم قراءة البيانات المحلية من هذا المتصفح.',noTripData:'لا توجد بيانات رحلات محفوظة',startDates:'ابدأ بتواريخ سفرك',emptyCopy:'أضف الإقامات السابقة والمحجوزة للحصول على نتيجة 90/180 فعلية. يبدأ SCHNGN فارغًا.',firstResult:'أول نتيجة مفيدة لك',firstResultCopy:'أضف تاريخي الدخول والخروج لإقامة واحدة. يُحتسب اليومان. تبقى تواريخك في هذا المتصفح.',addFirst:'أضف رحلتك الأولى',tryWhatIf:'جرّب سيناريو',latestSafeExit:'آخر خروج آمن',daysUsed:'الأيام المستخدمة',rollingWindow:'نافذة متحركة من 180 يومًا',needsAttention:'ما يحتاج إلى الانتباه',whyAnswer:'سبب هذه النتيجة',addTrip:'إضافة رحلة',showCalculation:'عرض الحساب',planAnother:'تخطيط رحلة أخرى',accountLoading:'الحساب…',localOnly:'محلي فقط',signIn:'تسجيل الدخول',syncing:'جارٍ المزامنة…',synced:'تمت المزامنة',syncPaused:'المزامنة متوقفة',reviewSync:'مراجعة المزامنة',accountReady:'الحساب جاهز'
};

const catalogs: Record<Locale, AppCatalog> = { en, fr, de, es, it, ru, tr, he, ar };

export function createAppUiTranslator(locale: Locale): (key: AppUiKey) => string {
  return (key) => catalogs[locale][key];
}
