import { SUPPORTED_LOCALES, type Locale } from './locales';

export type ContactUiKey =
  | 'nav'
  | 'metaTitle'
  | 'metaDescription'
  | 'eyebrow'
  | 'title'
  | 'intro'
  | 'typeLabel'
  | 'helpOption'
  | 'featureOption'
  | 'nameLabel'
  | 'optional'
  | 'emailLabel'
  | 'messageLabel'
  | 'messageHelp'
  | 'privacy'
  | 'verification'
  | 'submit'
  | 'sending'
  | 'successTitle'
  | 'successBody'
  | 'invalid'
  | 'verificationFailed'
  | 'rateLimited'
  | 'unavailable'
  | 'emailFallback';

type ContactUiCatalog = Record<ContactUiKey, string>;

const keys: ContactUiKey[] = [
  'nav','metaTitle','metaDescription','eyebrow','title','intro','typeLabel','helpOption','featureOption','nameLabel','optional','emailLabel','messageLabel','messageHelp','privacy','verification','submit','sending','successTitle','successBody','invalid','verificationFailed','rateLimited','unavailable','emailFallback'
];

function catalog(values: string[]): ContactUiCatalog {
  return Object.fromEntries(keys.map((key, index) => [key, values[index]])) as ContactUiCatalog;
}

const catalogs: Record<Locale, ContactUiCatalog> = {
  en: catalog(['Contact','Contact SCHNGN','Send a help request or suggest a feature to SCHNGN.','Help and ideas','How can we help?','Ask a question about using SCHNGN or tell us what would make it more useful.','Request type','I need help','I have a feature idea','Name','Optional','Email','Message','Please include enough detail for us to understand the request. Do not send passport, visa, or other sensitive document numbers.','Your email address and message are sent to SCHNGN support only so we can respond. Trip history is never attached automatically.','Security check','Send message','Sending…','Message sent','Thanks. Your message is on its way to SCHNGN support.','Check the highlighted fields and try again.','The security check expired or failed. Please try again.','Too many messages were sent recently. Please wait a minute and try again.','The contact form is temporarily unavailable. Please try again later.','You can also email us at']),
  fr: catalog(['Contact','Contacter SCHNGN','Envoyez une demande d’aide ou proposez une fonctionnalité à SCHNGN.','Aide et idées','Comment pouvons-nous vous aider ?','Posez une question sur SCHNGN ou dites-nous ce qui le rendrait plus utile.','Type de demande','J’ai besoin d’aide','J’ai une idée de fonctionnalité','Nom','Facultatif','E-mail','Message','Donnez assez de détails pour comprendre la demande. N’envoyez aucun numéro de passeport, de visa ou de document sensible.','Votre adresse e-mail et votre message sont envoyés uniquement au support SCHNGN afin de vous répondre. Aucun historique de voyage n’est joint automatiquement.','Vérification de sécurité','Envoyer le message','Envoi…','Message envoyé','Merci. Votre message est en route vers le support SCHNGN.','Vérifiez les champs signalés et réessayez.','La vérification de sécurité a expiré ou échoué. Réessayez.','Trop de messages ont été envoyés récemment. Attendez une minute puis réessayez.','Le formulaire de contact est temporairement indisponible. Réessayez plus tard.','Vous pouvez aussi nous écrire à']),
  de: catalog(['Kontakt','SCHNGN kontaktieren','Senden Sie eine Hilfeanfrage oder schlagen Sie eine Funktion für SCHNGN vor.','Hilfe und Ideen','Wie können wir helfen?','Stellen Sie eine Frage zu SCHNGN oder sagen Sie uns, was es nützlicher machen würde.','Art der Anfrage','Ich brauche Hilfe','Ich habe eine Funktionsidee','Name','Optional','E-Mail','Nachricht','Bitte beschreiben Sie Ihr Anliegen ausreichend. Senden Sie keine Pass-, Visa- oder anderen sensiblen Dokumentnummern.','Ihre E-Mail-Adresse und Nachricht gehen nur an den SCHNGN-Support, damit wir antworten können. Reiseverläufe werden nie automatisch angehängt.','Sicherheitsprüfung','Nachricht senden','Wird gesendet…','Nachricht gesendet','Danke. Ihre Nachricht ist auf dem Weg zum SCHNGN-Support.','Prüfen Sie die markierten Felder und versuchen Sie es erneut.','Die Sicherheitsprüfung ist abgelaufen oder fehlgeschlagen. Bitte erneut versuchen.','Kürzlich wurden zu viele Nachrichten gesendet. Warten Sie eine Minute und versuchen Sie es erneut.','Das Kontaktformular ist vorübergehend nicht verfügbar. Bitte später erneut versuchen.','Sie können uns auch mailen an']),
  es: catalog(['Contacto','Contactar con SCHNGN','Envía una solicitud de ayuda o sugiere una función para SCHNGN.','Ayuda e ideas','¿Cómo podemos ayudarte?','Haz una pregunta sobre SCHNGN o cuéntanos qué lo haría más útil.','Tipo de solicitud','Necesito ayuda','Tengo una idea para una función','Nombre','Opcional','Correo electrónico','Mensaje','Incluye detalles suficientes para entender la solicitud. No envíes números de pasaporte, visado u otros documentos sensibles.','Tu correo y mensaje se envían solo al equipo de SCHNGN para poder responder. Tu historial de viajes nunca se adjunta automáticamente.','Comprobación de seguridad','Enviar mensaje','Enviando…','Mensaje enviado','Gracias. Tu mensaje va de camino al equipo de SCHNGN.','Revisa los campos marcados e inténtalo de nuevo.','La comprobación de seguridad caducó o falló. Inténtalo de nuevo.','Se enviaron demasiados mensajes recientemente. Espera un minuto e inténtalo de nuevo.','El formulario de contacto no está disponible temporalmente. Inténtalo más tarde.','También puedes escribirnos a']),
  it: catalog(['Contatti','Contatta SCHNGN','Invia una richiesta di assistenza o suggerisci una funzione per SCHNGN.','Aiuto e idee','Come possiamo aiutarti?','Fai una domanda su SCHNGN o raccontaci cosa lo renderebbe più utile.','Tipo di richiesta','Ho bisogno di aiuto','Ho un’idea per una funzione','Nome','Facoltativo','Email','Messaggio','Inserisci dettagli sufficienti per capire la richiesta. Non inviare numeri di passaporto, visto o altri documenti sensibili.','Il tuo indirizzo email e il messaggio vengono inviati solo all’assistenza SCHNGN per poterti rispondere. La cronologia dei viaggi non viene mai allegata automaticamente.','Controllo di sicurezza','Invia messaggio','Invio…','Messaggio inviato','Grazie. Il messaggio è in viaggio verso l’assistenza SCHNGN.','Controlla i campi evidenziati e riprova.','Il controllo di sicurezza è scaduto o non riuscito. Riprova.','Sono stati inviati troppi messaggi di recente. Attendi un minuto e riprova.','Il modulo di contatto non è temporaneamente disponibile. Riprova più tardi.','Puoi anche scriverci a']),
  'pt-br': catalog(['Contato','Fale com a SCHNGN','Envie um pedido de ajuda ou sugira um recurso para a SCHNGN.','Ajuda e ideias','Como podemos ajudar?','Faça uma pergunta sobre a SCHNGN ou conte o que tornaria o serviço mais útil.','Tipo de solicitação','Preciso de ajuda','Tenho uma ideia de recurso','Nome','Opcional','E-mail','Mensagem','Inclua detalhes suficientes para entendermos o pedido. Não envie números de passaporte, visto ou outros documentos sensíveis.','Seu e-mail e sua mensagem são enviados apenas ao suporte da SCHNGN para que possamos responder. Seu histórico de viagens nunca é anexado automaticamente.','Verificação de segurança','Enviar mensagem','Enviando…','Mensagem enviada','Obrigado. Sua mensagem está a caminho do suporte da SCHNGN.','Confira os campos destacados e tente novamente.','A verificação de segurança expirou ou falhou. Tente novamente.','Muitas mensagens foram enviadas recentemente. Aguarde um minuto e tente novamente.','O formulário de contato está temporariamente indisponível. Tente mais tarde.','Você também pode enviar um e-mail para']),
  ru: catalog(['Связаться','Связаться с SCHNGN','Отправьте запрос о помощи или предложите новую функцию SCHNGN.','Помощь и идеи','Чем мы можем помочь?','Задайте вопрос о SCHNGN или расскажите, что сделало бы сервис полезнее.','Тип запроса','Мне нужна помощь','У меня есть идея функции','Имя','Необязательно','Электронная почта','Сообщение','Добавьте достаточно подробностей. Не отправляйте номера паспорта, визы или других конфиденциальных документов.','Адрес электронной почты и сообщение отправляются только в поддержку SCHNGN, чтобы мы могли ответить. История поездок никогда не прикрепляется автоматически.','Проверка безопасности','Отправить сообщение','Отправка…','Сообщение отправлено','Спасибо. Сообщение отправлено в поддержку SCHNGN.','Проверьте отмеченные поля и повторите попытку.','Проверка безопасности истекла или не удалась. Повторите попытку.','Недавно было отправлено слишком много сообщений. Подождите минуту и повторите попытку.','Форма связи временно недоступна. Попробуйте позже.','Также можно написать нам по адресу']),
  uk: catalog(['Зв’язок','Зв’язатися зі SCHNGN','Надішліть запит про допомогу або запропонуйте нову функцію SCHNGN.','Допомога та ідеї','Чим ми можемо допомогти?','Поставте запитання про SCHNGN або розкажіть, що зробило б сервіс кориснішим.','Тип запиту','Мені потрібна допомога','У мене є ідея функції','Ім’я','Необов’язково','Електронна пошта','Повідомлення','Додайте достатньо подробиць. Не надсилайте номери паспорта, візи чи інших конфіденційних документів.','Адреса електронної пошти й повідомлення надсилаються лише підтримці SCHNGN, щоб ми могли відповісти. Історія поїздок ніколи не додається автоматично.','Перевірка безпеки','Надіслати повідомлення','Надсилання…','Повідомлення надіслано','Дякуємо. Повідомлення надіслано підтримці SCHNGN.','Перевірте позначені поля й повторіть спробу.','Перевірка безпеки завершилася або не вдалася. Повторіть спробу.','Нещодавно надіслано забагато повідомлень. Зачекайте хвилину й повторіть спробу.','Форма зв’язку тимчасово недоступна. Спробуйте пізніше.','Також можете написати нам на']),
  tr: catalog(['İletişim','SCHNGN ile iletişime geçin','SCHNGN’ye yardım isteği gönderin veya bir özellik önerin.','Yardım ve fikirler','Nasıl yardımcı olabiliriz?','SCHNGN hakkında soru sorun veya onu daha yararlı kılacak önerinizi paylaşın.','İstek türü','Yardıma ihtiyacım var','Bir özellik fikrim var','Ad','İsteğe bağlı','E-posta','Mesaj','İsteği anlayabilmemiz için yeterli ayrıntı ekleyin. Pasaport, vize veya başka hassas belge numaraları göndermeyin.','E-posta adresiniz ve mesajınız yalnızca yanıt verebilmemiz için SCHNGN desteğine gönderilir. Seyahat geçmişiniz hiçbir zaman otomatik eklenmez.','Güvenlik kontrolü','Mesaj gönder','Gönderiliyor…','Mesaj gönderildi','Teşekkürler. Mesajınız SCHNGN desteğine gönderildi.','İşaretli alanları kontrol edip yeniden deneyin.','Güvenlik kontrolünün süresi doldu veya kontrol başarısız oldu. Yeniden deneyin.','Kısa süre içinde çok fazla mesaj gönderildi. Bir dakika bekleyip yeniden deneyin.','İletişim formu geçici olarak kullanılamıyor. Daha sonra yeniden deneyin.','Bize şu adresten de e-posta gönderebilirsiniz']),
  sr: catalog(['Kontakt','Kontaktirajte SCHNGN','Pošaljite zahtev za pomoć ili predložite novu funkciju za SCHNGN.','Pomoć i ideje','Kako možemo da pomognemo?','Postavite pitanje o SCHNGN-u ili nam recite šta bi ga učinilo korisnijim.','Vrsta zahteva','Potrebna mi je pomoć','Imam ideju za funkciju','Ime','Opciono','E-pošta','Poruka','Dodajte dovoljno detalja da razumemo zahtev. Ne šaljite brojeve pasoša, viza ili drugih osetljivih dokumenata.','Vaša adresa e-pošte i poruka šalju se samo SCHNGN podršci radi odgovora. Istorija putovanja se nikada ne prilaže automatski.','Bezbednosna provera','Pošalji poruku','Slanje…','Poruka je poslata','Hvala. Vaša poruka je poslata SCHNGN podršci.','Proverite označena polja i pokušajte ponovo.','Bezbednosna provera je istekla ili nije uspela. Pokušajte ponovo.','Nedavno je poslato previše poruka. Sačekajte minut i pokušajte ponovo.','Kontakt obrazac je privremeno nedostupan. Pokušajte kasnije.','Možete nam pisati i na']),
  sq: catalog(['Kontakt','Kontaktoni SCHNGN','Dërgoni një kërkesë për ndihmë ose sugjeroni një veçori për SCHNGN.','Ndihmë dhe ide','Si mund t’ju ndihmojmë?','Bëni një pyetje për SCHNGN ose na tregoni çfarë do ta bënte më të dobishëm.','Lloji i kërkesës','Kam nevojë për ndihmë','Kam një ide për veçori','Emri','Opsionale','Email','Mesazhi','Jepni hollësi të mjaftueshme. Mos dërgoni numra pasaporte, vize ose dokumentesh të tjera të ndjeshme.','Adresa juaj e emailit dhe mesazhi i dërgohen vetëm mbështetjes së SCHNGN për t’ju përgjigjur. Historiku i udhëtimeve nuk bashkëngjitet kurrë automatikisht.','Kontroll sigurie','Dërgo mesazhin','Po dërgohet…','Mesazhi u dërgua','Faleminderit. Mesazhi juaj iu dërgua mbështetjes së SCHNGN.','Kontrolloni fushat e shënuara dhe provoni përsëri.','Kontrolli i sigurisë skadoi ose dështoi. Provoni përsëri.','Janë dërguar shumë mesazhe së fundi. Prisni një minutë dhe provoni përsëri.','Formulari i kontaktit është përkohësisht i padisponueshëm. Provoni më vonë.','Mund të na shkruani edhe në']),
  ka: catalog(['კონტაქტი','დაუკავშირდით SCHNGN-ს','გაგზავნეთ დახმარების მოთხოვნა ან შემოგვთავაზეთ ახალი ფუნქცია.','დახმარება და იდეები','როგორ შეგვიძლია დაგეხმაროთ?','დასვით კითხვა SCHNGN-ის შესახებ ან გვითხარით, რა გახდიდა მას უფრო სასარგებლოს.','მოთხოვნის ტიპი','დახმარება მჭირდება','ფუნქციის იდეა მაქვს','სახელი','არასავალდებულო','ელფოსტა','შეტყობინება','მიუთითეთ საკმარისი დეტალი. ნუ გამოგზავნით პასპორტის, ვიზის ან სხვა მგრძნობიარე დოკუმენტის ნომრებს.','თქვენი ელფოსტა და შეტყობინება მხოლოდ SCHNGN-ის მხარდაჭერას ეგზავნება პასუხისთვის. მოგზაურობის ისტორია ავტომატურად არასდროს ერთვის.','უსაფრთხოების შემოწმება','შეტყობინების გაგზავნა','იგზავნება…','შეტყობინება გაიგზავნა','გმადლობთ. თქვენი შეტყობინება SCHNGN-ის მხარდაჭერას გაეგზავნა.','შეამოწმეთ მონიშნული ველები და ხელახლა სცადეთ.','უსაფრთხოების შემოწმება ამოიწურა ან ვერ შესრულდა. ხელახლა სცადეთ.','ბოლო დროს ძალიან ბევრი შეტყობინება გაიგზავნა. მოიცადეთ ერთი წუთი და სცადეთ ხელახლა.','კონტაქტის ფორმა დროებით მიუწვდომელია. მოგვიანებით სცადეთ.','ასევე შეგიძლიათ მოგვწეროთ მისამართზე']),
  'zh-cn': catalog(['联系','联系 SCHNGN','向 SCHNGN 发送帮助请求或提出功能建议。','帮助与建议','我们能为你做什么？','询问如何使用 SCHNGN，或告诉我们怎样能让它更实用。','请求类型','我需要帮助','我有功能建议','姓名','选填','电子邮箱','留言','请提供足够的细节。请勿发送护照、签证或其他敏感证件号码。','你的邮箱和留言只会发送给 SCHNGN 支持团队，以便我们回复。行程历史绝不会自动附加。','安全验证','发送留言','正在发送…','留言已发送','谢谢。你的留言已发送给 SCHNGN 支持团队。','请检查标出的字段后重试。','安全验证已过期或失败，请重试。','最近发送的留言过多，请等待一分钟后重试。','联系表单暂时不可用，请稍后再试。','你也可以发送邮件至']),
  ja: catalog(['お問い合わせ','SCHNGNへのお問い合わせ','SCHNGNへのサポート依頼または機能のご提案をお送りください。','サポートとご提案','どのようなご用件ですか？','SCHNGNの使い方に関する質問や、より便利にするためのご意見をお寄せください。','お問い合わせの種類','使い方について質問したい','機能を提案したい','お名前','任意','メールアドレス','メッセージ','内容が分かるよう詳しくご記入ください。パスポート、ビザ、その他の機密性の高い書類番号は送らないでください。','メールアドレスとメッセージは返信のためSCHNGNサポートにのみ送信されます。旅行履歴が自動添付されることはありません。','セキュリティ確認','送信する','送信中…','送信しました','ありがとうございます。SCHNGNサポートへ送信しました。','入力内容を確認して、もう一度お試しください。','セキュリティ確認が期限切れか失敗しました。もう一度お試しください。','短時間に多くのメッセージが送信されました。1分待ってからお試しください。','お問い合わせフォームは一時的に利用できません。後でもう一度お試しください。','メールでもお問い合わせいただけます']),
  ko: catalog(['문의','SCHNGN 문의','SCHNGN에 도움을 요청하거나 기능을 제안하세요.','도움 및 제안','무엇을 도와드릴까요?','SCHNGN 사용에 관해 질문하거나 더 유용하게 만들 아이디어를 알려주세요.','요청 유형','도움이 필요해요','기능 아이디어가 있어요','이름','선택 사항','이메일','메시지','요청을 이해할 수 있도록 자세히 적어 주세요. 여권, 비자 또는 기타 민감한 문서 번호는 보내지 마세요.','이메일 주소와 메시지는 답변을 위해 SCHNGN 지원팀에만 전송됩니다. 여행 기록은 자동으로 첨부되지 않습니다.','보안 확인','메시지 보내기','보내는 중…','메시지를 보냈습니다','감사합니다. 메시지가 SCHNGN 지원팀으로 전송되었습니다.','표시된 항목을 확인하고 다시 시도하세요.','보안 확인이 만료되었거나 실패했습니다. 다시 시도하세요.','최근 너무 많은 메시지가 전송되었습니다. 1분 후 다시 시도하세요.','문의 양식을 일시적으로 사용할 수 없습니다. 나중에 다시 시도하세요.','이메일로도 문의할 수 있습니다']),
  he: catalog(['יצירת קשר','יצירת קשר עם SCHNGN','שלחו בקשת עזרה או הציעו תכונה חדשה ל‑SCHNGN.','עזרה ורעיונות','כיצד נוכל לעזור?','שאלו שאלה על השימוש ב‑SCHNGN או ספרו לנו מה יהפוך אותו לשימושי יותר.','סוג הפנייה','דרושה לי עזרה','יש לי רעיון לתכונה','שם','לא חובה','דוא״ל','הודעה','הוסיפו מספיק פרטים כדי שנבין את הפנייה. אל תשלחו מספרי דרכון, אשרה או מסמכים רגישים אחרים.','כתובת הדוא״ל וההודעה נשלחות רק לתמיכת SCHNGN כדי שנוכל להשיב. היסטוריית הנסיעות לעולם אינה מצורפת אוטומטית.','בדיקת אבטחה','שליחת הודעה','שולח…','ההודעה נשלחה','תודה. ההודעה נשלחה לתמיכת SCHNGN.','בדקו את השדות המסומנים ונסו שוב.','בדיקת האבטחה פגה או נכשלה. נסו שוב.','נשלחו יותר מדי הודעות לאחרונה. המתינו דקה ונסו שוב.','טופס יצירת הקשר אינו זמין זמנית. נסו שוב מאוחר יותר.','אפשר גם לשלוח לנו דוא״ל אל']),
  ar: catalog(['اتصل بنا','التواصل مع SCHNGN','أرسل طلب مساعدة أو اقترح ميزة جديدة لـ SCHNGN.','المساعدة والأفكار','كيف يمكننا مساعدتك؟','اطرح سؤالًا عن استخدام SCHNGN أو أخبرنا بما يجعله أكثر فائدة.','نوع الطلب','أحتاج إلى مساعدة','لدي فكرة لميزة','الاسم','اختياري','البريد الإلكتروني','الرسالة','أضف تفاصيل كافية لفهم الطلب. لا ترسل أرقام جواز السفر أو التأشيرة أو أي مستندات حساسة أخرى.','يُرسل بريدك الإلكتروني ورسالتك إلى دعم SCHNGN فقط كي نتمكن من الرد. لا يُرفق سجل رحلاتك تلقائيًا أبدًا.','فحص الأمان','إرسال الرسالة','جارٍ الإرسال…','تم إرسال الرسالة','شكرًا. أُرسلت رسالتك إلى دعم SCHNGN.','تحقق من الحقول المحددة وحاول مرة أخرى.','انتهت صلاحية فحص الأمان أو فشل. حاول مرة أخرى.','أُرسلت رسائل كثيرة مؤخرًا. انتظر دقيقة ثم حاول مرة أخرى.','نموذج التواصل غير متاح مؤقتًا. حاول مرة أخرى لاحقًا.','يمكنك أيضًا مراسلتنا على'])
};

export function contactUi(locale: Locale): ContactUiCatalog {
  return catalogs[locale];
}

export function contactUiCatalogLengths(): Record<Locale, number> {
  return Object.fromEntries(SUPPORTED_LOCALES.map((locale) => [locale, Object.keys(catalogs[locale]).length])) as Record<Locale, number>;
}
