import { SUPPORTED_LOCALES, type Locale } from './locales';
import { deepTranslateExtended, translateExtended } from './extendedLocaleStrings';

export interface RuleScenario {
  title: string;
  body: string;
  result: string;
}

interface RulesCatalog {
  title: string;
  intro: string;
  ordinaryTitle: string;
  ordinaryCopy: string;
  windowTitle: string;
  windowCopy: string;
  countingTitle: string;
  countingCopy: string;
  journeyTitle: string;
  journeyCopy: string;
  overlapTitle: string;
  overlapCopy: string;
  scopeTitle: string;
  scopeCopy: string;
  animationLabel: string;
  scenarios: readonly [RuleScenario, RuleScenario, RuleScenario, RuleScenario];
}

const catalogs: Partial<Record<Locale, RulesCatalog>> & { en: RulesCatalog } = {
  en: {
    title: 'The rules behind the calculation',
    intro: 'SCHNGN applies the ordinary Schengen short-stay 90/180-day calculation to the dates you enter. These are the assumptions used every time the timeline changes.',
    ordinaryTitle: '90 days in any 180 days', ordinaryCopy: 'For each calendar day, the app looks back across that day and the previous 179 days. No more than 90 counted presence days may fall inside that inclusive window.',
    windowTitle: 'Entry and exit both count', windowCopy: 'A presence day counts even if you arrive late or leave early. A same-day visit therefore uses one day.',
    countingTitle: 'Only full days outside are excluded', countingCopy: 'Moving between Schengen countries does not end a stay. A break removes only complete calendar days spent outside the Schengen Area.',
    journeyTitle: 'Old days return one by one', journeyCopy: 'A counted day becomes available again when it moves beyond the rolling 180-day window. The return date depends on the rest of your travel history.',
    overlapTitle: 'A physical day is counted once', overlapCopy: 'If saved trips overlap, the shared dates are de-duplicated. Overlapping records never create extra presence days.',
    scopeTitle: 'Ordinary short stays only', scopeCopy: 'Residence permits, long-stay or national visas, bilateral waivers, work, study, asylum and border-officer decisions can change the result. Verify those situations with official sources.',
    animationLabel: 'Animated examples of the Schengen calculation rules',
    scenarios: [
      { title: 'Arrival and departure are inclusive', body: 'A stay from 1–10 June uses every calendar day, including both boundary dates.', result: '10 counted days' },
      { title: 'Countries do not reset the clock', body: 'Italy followed by Austria without leaving Schengen remains one continuous presence.', result: '1 continuous stay' },
      { title: 'Complete days outside pause counting', body: 'The exit and re-entry days count; only the complete days between them are excluded.', result: '2 days outside' },
      { title: 'Days age out of the rolling window', body: 'When an old presence day moves past day 180, one day becomes available again.', result: '1 day returned' }
    ]
  },
  fr: {
    title:'Les règles du calcul',intro:'SCHNGN applique aux dates saisies le calcul ordinaire des courts séjours Schengen selon la règle 90/180. Ces hypothèses sont utilisées à chaque modification.',ordinaryTitle:'90 jours sur toute période de 180 jours',ordinaryCopy:'Pour chaque date, l’application examine ce jour et les 179 jours précédents. Cette fenêtre inclusive ne peut contenir plus de 90 jours de présence.',windowTitle:'L’entrée et la sortie comptent',windowCopy:'Un jour compte même en cas d’arrivée tardive ou de départ matinal. Une visite aller-retour dans la journée utilise donc un jour.',countingTitle:'Seuls les jours complets hors Schengen sont exclus',countingCopy:'Passer d’un pays Schengen à un autre ne termine pas le séjour. Une pause retire uniquement les jours civils complets passés hors Schengen.',journeyTitle:'Les anciens jours reviennent un par un',journeyCopy:'Un jour redevient disponible lorsqu’il sort de la fenêtre glissante de 180 jours. Sa date de retour dépend du reste de l’historique.',overlapTitle:'Un jour réel ne compte qu’une fois',overlapCopy:'Si des voyages se chevauchent, les dates communes sont dédupliquées et ne créent jamais de jours supplémentaires.',scopeTitle:'Courts séjours ordinaires uniquement',scopeCopy:'Titres de séjour, visas nationaux ou de long séjour, accords bilatéraux, travail, études, asile et décisions frontalières peuvent modifier le résultat. Consultez les sources officielles.',animationLabel:'Exemples animés des règles de calcul Schengen',scenarios:[{title:'Arrivée et départ inclus',body:'Un séjour du 1er au 10 juin utilise chaque jour civil, dates limites comprises.',result:'10 jours comptés'},{title:'Changer de pays ne remet pas le compteur à zéro',body:'L’Italie puis l’Autriche sans quitter Schengen restent une présence continue.',result:'1 séjour continu'},{title:'Les jours complets à l’extérieur interrompent le décompte',body:'Les jours de sortie et de retour comptent ; seuls les jours complets entre les deux sont exclus.',result:'2 jours à l’extérieur'},{title:'Les jours sortent de la fenêtre glissante',body:'Lorsqu’un ancien jour dépasse le jour 180, un jour redevient disponible.',result:'1 jour rendu'}]
  },
  de: {
    title:'Die Regeln hinter der Berechnung',intro:'SCHNGN wendet auf Ihre Daten die gewöhnliche Schengen-Kurzaufenthaltsregel 90/180 an. Diese Annahmen gelten bei jeder Änderung der Zeitleiste.',ordinaryTitle:'90 Tage in jedem 180-Tage-Zeitraum',ordinaryCopy:'Für jeden Kalendertag betrachtet die App diesen Tag und die 179 vorherigen Tage. In diesem inklusiven Fenster dürfen höchstens 90 Anwesenheitstage liegen.',windowTitle:'Einreise und Ausreise zählen',windowCopy:'Ein Tag zählt auch bei später Ankunft oder früher Abreise. Ein Besuch am selben Tag verbraucht daher einen Tag.',countingTitle:'Nur volle Tage außerhalb zählen nicht',countingCopy:'Reisen zwischen Schengen-Ländern beenden den Aufenthalt nicht. Eine Pause entfernt nur vollständige Kalendertage außerhalb des Schengen-Raums.',journeyTitle:'Alte Tage kehren einzeln zurück',journeyCopy:'Ein Tag wird wieder verfügbar, sobald er außerhalb des rollierenden 180-Tage-Fensters liegt. Das Datum hängt vom gesamten Reiseverlauf ab.',overlapTitle:'Ein realer Tag zählt einmal',overlapCopy:'Überschneiden sich gespeicherte Reisen, werden gemeinsame Daten dedupliziert und nie doppelt gezählt.',scopeTitle:'Nur gewöhnliche Kurzaufenthalte',scopeCopy:'Aufenthaltstitel, nationale oder Langzeitvisa, bilaterale Abkommen, Arbeit, Studium, Asyl und Grenzentscheidungen können das Ergebnis ändern. Prüfen Sie offizielle Quellen.',animationLabel:'Animierte Beispiele der Schengen-Berechnungsregeln',scenarios:[{title:'Einreise und Ausreise sind inklusive',body:'Ein Aufenthalt vom 1. bis 10. Juni nutzt jeden Kalendertag einschließlich beider Grenzen.',result:'10 gezählte Tage'},{title:'Länderwechsel setzt die Uhr nicht zurück',body:'Italien und danach Österreich ohne Schengen zu verlassen bleibt ein durchgehender Aufenthalt.',result:'1 durchgehender Aufenthalt'},{title:'Volle Tage außerhalb pausieren die Zählung',body:'Ausreise- und Wiedereinreisetag zählen; nur die vollen Tage dazwischen sind ausgeschlossen.',result:'2 Tage außerhalb'},{title:'Tage fallen aus dem rollierenden Fenster',body:'Sobald ein alter Anwesenheitstag Tag 180 überschreitet, wird ein Tag wieder verfügbar.',result:'1 Tag zurück'}]
  },
  es: {
    title:'Las reglas del cálculo',intro:'SCHNGN aplica a tus fechas el cálculo ordinario de estancias cortas Schengen 90/180. Estas reglas se usan cada vez que cambia la cronología.',ordinaryTitle:'90 días en cualquier período de 180',ordinaryCopy:'Para cada fecha, la aplicación revisa ese día y los 179 anteriores. La ventana inclusiva no puede contener más de 90 días de presencia.',windowTitle:'La entrada y la salida cuentan',windowCopy:'Un día cuenta aunque llegues tarde o salgas temprano. Una visita de ida y vuelta en el día utiliza un día.',countingTitle:'Solo se excluyen los días completos fuera',countingCopy:'Viajar entre países Schengen no termina una estancia. Una pausa elimina únicamente los días naturales completos fuera del espacio Schengen.',journeyTitle:'Los días antiguos vuelven uno a uno',journeyCopy:'Un día vuelve a estar disponible cuando sale de la ventana móvil de 180 días. La fecha depende del resto del historial.',overlapTitle:'Cada día físico cuenta una vez',overlapCopy:'Si los viajes guardados se solapan, las fechas compartidas se deduplican y nunca generan días extra.',scopeTitle:'Solo estancias cortas ordinarias',scopeCopy:'Permisos de residencia, visados nacionales o de larga duración, acuerdos bilaterales, trabajo, estudios, asilo y decisiones fronterizas pueden cambiar el resultado. Consulta fuentes oficiales.',animationLabel:'Ejemplos animados de las reglas de cálculo Schengen',scenarios:[{title:'Entrada y salida incluidas',body:'Una estancia del 1 al 10 de junio utiliza cada día natural, incluidos ambos límites.',result:'10 días contados'},{title:'Cambiar de país no reinicia el contador',body:'Italia seguida de Austria sin salir de Schengen sigue siendo una presencia continua.',result:'1 estancia continua'},{title:'Los días completos fuera detienen el recuento',body:'Los días de salida y reentrada cuentan; solo se excluyen los días completos intermedios.',result:'2 días fuera'},{title:'Los días salen de la ventana móvil',body:'Cuando un día antiguo supera el día 180, vuelve a estar disponible un día.',result:'1 día recuperado'}]
  },
  it: {
    title:'Le regole del calcolo',intro:'SCHNGN applica alle date inserite il calcolo ordinario dei soggiorni brevi Schengen 90/180. Queste regole valgono a ogni modifica della cronologia.',ordinaryTitle:'90 giorni in qualsiasi periodo di 180',ordinaryCopy:'Per ogni data, l’app considera quel giorno e i 179 precedenti. La finestra inclusiva non può contenere più di 90 giorni di presenza.',windowTitle:'Ingresso e uscita contano',windowCopy:'Un giorno conta anche con arrivo tardivo o partenza anticipata. Una visita in giornata usa quindi un giorno.',countingTitle:'Sono esclusi solo i giorni interi fuori',countingCopy:'Spostarsi tra paesi Schengen non termina il soggiorno. Una pausa rimuove solo i giorni di calendario completi fuori dall’area Schengen.',journeyTitle:'I giorni vecchi tornano uno alla volta',journeyCopy:'Un giorno torna disponibile quando esce dalla finestra mobile di 180 giorni. La data dipende dal resto della cronologia.',overlapTitle:'Ogni giorno reale conta una volta',overlapCopy:'Se i viaggi salvati si sovrappongono, le date comuni vengono deduplicate e non creano giorni extra.',scopeTitle:'Solo soggiorni brevi ordinari',scopeCopy:'Permessi di soggiorno, visti nazionali o di lunga durata, accordi bilaterali, lavoro, studio, asilo e decisioni di frontiera possono cambiare il risultato. Verifica le fonti ufficiali.',animationLabel:'Esempi animati delle regole di calcolo Schengen',scenarios:[{title:'Ingresso e uscita sono inclusi',body:'Un soggiorno dal 1 al 10 giugno usa ogni giorno di calendario, compresi entrambi i limiti.',result:'10 giorni conteggiati'},{title:'Cambiare paese non azzera il conteggio',body:'Italia seguita da Austria senza uscire da Schengen resta una presenza continua.',result:'1 soggiorno continuo'},{title:'I giorni interi fuori sospendono il conteggio',body:'I giorni di uscita e rientro contano; solo i giorni interi intermedi sono esclusi.',result:'2 giorni fuori'},{title:'I giorni escono dalla finestra mobile',body:'Quando un vecchio giorno supera il giorno 180, un giorno torna disponibile.',result:'1 giorno restituito'}]
  },
  ru: {
    title:'Правила расчёта',intro:'SCHNGN применяет к указанным датам обычное правило краткосрочного пребывания 90/180. Эти допущения используются при каждом изменении шкалы времени.',ordinaryTitle:'90 дней в любом периоде 180 дней',ordinaryCopy:'Для каждой даты приложение рассматривает этот день и предыдущие 179 дней. В этом включительном окне может быть не более 90 дней присутствия.',windowTitle:'Дни въезда и выезда учитываются',windowCopy:'День учитывается даже при позднем въезде или раннем выезде. Поездка в один день использует один день.',countingTitle:'Исключаются только полные дни вне Шенгена',countingCopy:'Переезд между странами Шенгена не завершает пребывание. Перерыв исключает только полные календарные дни вне зоны.',journeyTitle:'Старые дни возвращаются по одному',journeyCopy:'День снова становится доступным, когда выходит за пределы скользящего окна 180 дней. Дата зависит от всей истории поездок.',overlapTitle:'Физический день учитывается один раз',overlapCopy:'Если сохранённые поездки пересекаются, общие даты устраняются и не создают лишних дней.',scopeTitle:'Только обычные краткосрочные поездки',scopeCopy:'ВНЖ, национальные и долгосрочные визы, двусторонние соглашения, работа, учёба, убежище и решения пограничников могут изменить результат. Проверяйте официальные источники.',animationLabel:'Анимированные примеры правил расчёта Шенгена',scenarios:[{title:'Въезд и выезд включены',body:'Поездка с 1 по 10 июня использует каждый календарный день, включая обе границы.',result:'10 учтённых дней'},{title:'Смена страны не сбрасывает счётчик',body:'Италия, затем Австрия без выезда из Шенгена — одно непрерывное пребывание.',result:'1 непрерывная поездка'},{title:'Полные дни снаружи приостанавливают счёт',body:'Дни выезда и повторного въезда учитываются; исключаются только полные дни между ними.',result:'2 дня вне Шенгена'},{title:'Дни выходят из скользящего окна',body:'Когда старый день выходит за пределы 180 дней, один день становится доступным.',result:'1 день возвращён'}]
  },
  tr: {
    title:'Hesabın dayandığı kurallar',intro:'SCHNGN, girdiğiniz tarihlere normal Schengen kısa kalış 90/180 hesabını uygular. Zaman çizelgesi her değiştiğinde bu varsayımlar kullanılır.',ordinaryTitle:'Her 180 günde en fazla 90 gün',ordinaryCopy:'Uygulama her tarih için o günü ve önceki 179 günü inceler. Bu dahilî pencerede en fazla 90 bulunma günü olabilir.',windowTitle:'Giriş ve çıkış günleri sayılır',windowCopy:'Geç giriş veya erken çıkış olsa bile gün sayılır. Aynı gün gidip gelmek bu nedenle bir gün kullanır.',countingTitle:'Yalnızca dışarıdaki tam günler hariçtir',countingCopy:'Schengen ülkeleri arasında geçiş kalışı bitirmez. Bir ara yalnızca Schengen dışında geçirilen tam takvim günlerini çıkarır.',journeyTitle:'Eski günler tek tek geri döner',journeyCopy:'Sayılan bir gün, kayan 180 günlük pencerenin dışına çıktığında yeniden kullanılabilir. Tarih seyahat geçmişinin tamamına bağlıdır.',overlapTitle:'Her gerçek gün bir kez sayılır',overlapCopy:'Kayıtlı seyahatler çakışırsa ortak tarihler tekilleştirilir ve fazladan gün oluşturmaz.',scopeTitle:'Yalnızca normal kısa kalışlar',scopeCopy:'Oturma izinleri, ulusal veya uzun süreli vizeler, ikili muafiyetler, çalışma, eğitim, sığınma ve sınır görevlisi kararları sonucu değiştirebilir. Resmî kaynakları kontrol edin.',animationLabel:'Schengen hesaplama kurallarının animasyonlu örnekleri',scenarios:[{title:'Giriş ve çıkış dahildir',body:'1–10 Haziran arasındaki bir kalış, iki sınır tarihi dahil her takvim gününü kullanır.',result:'10 sayılan gün'},{title:'Ülke değiştirmek sayacı sıfırlamaz',body:'Schengen’den çıkmadan İtalya’dan Avusturya’ya geçiş tek bir kesintisiz kalıştır.',result:'1 kesintisiz kalış'},{title:'Dışarıdaki tam günler sayımı durdurur',body:'Çıkış ve yeniden giriş günleri sayılır; yalnızca aradaki tam günler hariçtir.',result:'2 gün dışarıda'},{title:'Günler kayan pencereden çıkar',body:'Eski bir bulunma günü 180 günün dışına çıktığında bir gün yeniden kullanılabilir.',result:'1 gün geri döndü'}]
  },
  he: {
    title:'הכללים שמאחורי החישוב',intro:'SCHNGN מחיל על התאריכים שהוזנו את חישוב השהייה הקצרה הרגיל של 90/180. ההנחות האלה משמשות בכל שינוי בציר הזמן.',ordinaryTitle:'90 ימים בכל תקופה של 180 ימים',ordinaryCopy:'לכל תאריך האפליקציה בודקת את אותו יום ואת 179 הימים שלפניו. בחלון הכולל לא יכולים להופיע יותר מ־90 ימי נוכחות.',windowTitle:'גם יום הכניסה וגם יום היציאה נספרים',windowCopy:'יום נספר גם אם נכנסים מאוחר או יוצאים מוקדם. לכן ביקור באותו יום משתמש ביום אחד.',countingTitle:'רק ימים מלאים מחוץ לשנגן אינם נספרים',countingCopy:'מעבר בין מדינות שנגן אינו מסיים שהייה. הפסקה מוציאה מהחישוב רק ימים קלנדריים מלאים מחוץ לאזור.',journeyTitle:'ימים ישנים חוזרים אחד־אחד',journeyCopy:'יום חוזר להיות זמין כשהוא יוצא מחלון 180 הימים המתגלגל. התאריך תלוי בשאר היסטוריית הנסיעות.',overlapTitle:'כל יום ממשי נספר פעם אחת',overlapCopy:'אם נסיעות שמורות חופפות, התאריכים המשותפים מאוחדים ואינם יוצרים ימים נוספים.',scopeTitle:'שהיות קצרות רגילות בלבד',scopeCopy:'היתרי שהייה, אשרות לאומיות או ארוכות, הסכמים דו־צדדיים, עבודה, לימודים, מקלט והחלטות ביקורת הגבולות יכולים לשנות את התוצאה. בדקו מקורות רשמיים.',animationLabel:'דוגמאות מונפשות לכללי החישוב של שנגן',scenarios:[{title:'הכניסה והיציאה כלולות',body:'שהייה מ־1 עד 10 ביוני משתמשת בכל יום קלנדרי, כולל שני תאריכי הגבול.',result:'10 ימים שנספרו'},{title:'מעבר מדינה לא מאפס את השעון',body:'איטליה ואחריה אוסטריה בלי לצאת משנגן הן נוכחות רצופה אחת.',result:'שהייה רצופה אחת'},{title:'ימים מלאים בחוץ עוצרים את הספירה',body:'ימי היציאה והכניסה מחדש נספרים; רק הימים המלאים ביניהם מוחרגים.',result:'יומיים בחוץ'},{title:'ימים יוצאים מהחלון המתגלגל',body:'כשיום נוכחות ישן עובר את יום 180, יום אחד חוזר להיות זמין.',result:'יום אחד חזר'}]
  },
  ar: {
    title:'القواعد التي يقوم عليها الحساب',intro:'يطبق SCHNGN على التواريخ المدخلة حساب الإقامة القصيرة العادي 90/180. تُستخدم هذه الافتراضات مع كل تغيير في المخطط الزمني.',ordinaryTitle:'90 يومًا في أي فترة من 180 يومًا',ordinaryCopy:'تفحص الحاسبة كل يوم مع الأيام الـ179 السابقة. لا يجوز أن تحتوي هذه النافذة الشاملة على أكثر من 90 يوم حضور.',windowTitle:'يُحتسب يوما الدخول والخروج',windowCopy:'يُحتسب اليوم حتى عند الدخول المتأخر أو الخروج المبكر. لذلك تستخدم زيارة اليوم الواحد يومًا واحدًا.',countingTitle:'تُستبعد الأيام الكاملة خارج شنغن فقط',countingCopy:'لا ينهي الانتقال بين دول شنغن الإقامة. تستبعد الفترة فقط الأيام التقويمية الكاملة خارج المنطقة.',journeyTitle:'تعود الأيام القديمة واحدًا تلو الآخر',journeyCopy:'يصبح اليوم متاحًا من جديد عندما يخرج من نافذة 180 يومًا المتحركة. يعتمد تاريخ العودة على بقية سجل السفر.',overlapTitle:'يُحتسب اليوم الفعلي مرة واحدة',overlapCopy:'إذا تداخلت الرحلات المحفوظة، تُوحّد التواريخ المشتركة ولا تنشئ أيام حضور إضافية.',scopeTitle:'للإقامات القصيرة العادية فقط',scopeCopy:'قد تغيّر تصاريح الإقامة والتأشيرات الوطنية أو الطويلة والإعفاءات الثنائية والعمل والدراسة واللجوء وقرارات موظفي الحدود النتيجة. راجع المصادر الرسمية.',animationLabel:'أمثلة متحركة لقواعد حساب شنغن',scenarios:[{title:'الدخول والخروج مشمولان',body:'تستخدم الإقامة من 1 إلى 10 يونيو كل يوم تقويمي، بما في ذلك تاريخا البداية والنهاية.',result:'10 أيام محتسبة'},{title:'تغيير الدولة لا يعيد ضبط العداد',body:'إيطاليا ثم النمسا من دون مغادرة شنغن تظل إقامة واحدة متصلة.',result:'إقامة متصلة واحدة'},{title:'الأيام الكاملة في الخارج توقف العد',body:'يُحتسب يوما الخروج والعودة؛ وتُستبعد الأيام الكاملة الواقعة بينهما فقط.',result:'يومان في الخارج'},{title:'تخرج الأيام من النافذة المتحركة',body:'عندما يتجاوز يوم حضور قديم اليوم 180، يصبح يوم واحد متاحًا من جديد.',result:'عاد يوم واحد'}]
  }
};

const explainerTitles: Partial<Record<Locale, string>> & { en: string } = {
  en: 'Explainer', fr: 'Explication', de: 'Erklärung', es: 'Explicación', it: 'Spiegazione',
  ru: 'Объяснение', tr: 'Açıklama', he: 'הסבר', ar: 'الشرح'
};

const explainerAnimationLabels: Partial<Record<Locale, string>> & { en: string } = {
  en: 'Animated trip cards and timeline examples',
  fr: 'Cartes de voyage et chronologies animées',
  de: 'Animierte Reisekarten und Zeitleisten',
  es: 'Tarjetas de viaje y cronologías animadas',
  it: 'Schede di viaggio e cronologie animate',
  ru: 'Анимированные карточки поездок и шкалы времени',
  tr: 'Animasyonlu seyahat kartları ve zaman çizelgeleri',
  he: 'כרטיסי נסיעה וצירי זמן מונפשים',
  ar: 'بطاقات رحلات ومخططات زمنية متحركة'
};

export function rulesUi(locale: Locale): RulesCatalog {
  const catalog = catalogs[locale] ?? deepTranslateExtended(locale, catalogs.en);
  return {
    ...catalog,
    title: explainerTitles[locale] ?? translateExtended(locale, explainerTitles.en),
    animationLabel: explainerAnimationLabels[locale] ?? translateExtended(locale, explainerAnimationLabels.en)
  };
}

export function rulesCatalogLengths(): Record<Locale, number> {
  return Object.fromEntries(SUPPORTED_LOCALES.map((locale) => [locale, Object.keys(catalogs.en).length])) as Record<Locale, number>;
}
